apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fl-config
  namespace: fl-pg-ns
data:
  AUTHOR: Andrey
  DB_SERVICE_PATH: pg-db
  DB_USER: postgres
  DB_NAME: test_db1
  DB_PORT: 5432
  DB_PASSWORD: Qwer1234