---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrey-flask-deployment
  labels:
    app: andrey-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: achskv/flask_test:latest
        ports:
        - containerPort: 5000