---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: fl-pg-ns
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80