---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-flask-deployment
  namespace: fl-pg-ns
  labels:
    app: web-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: achskv/flask_test:1.1.1
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: web-fl-config
        
